services:
  micro_step_db:
    image: postgres:latest
    container_name: micro_step_db
    ports:
      - "54325:5432"
    environment:
      POSTGRES_DB: micro_step_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - micro_step_db:/var/lib/postgresql
    restart: unless-stopped

  micro_step_adminer:
    image: adminer:latest
    container_name: micro_step_adminer
    depends_on:
      - micro_step_db
    ports:
      - "8882:8080"
    restart: unless-stopped

volumes:
  micro_step_db:
